apiVersion: v1
kind: Pod
metadata:
  name: fail
spec:
  restartPolicy: Never
  containers:
    - name: fail
      image: ubuntu:16.04
      args:
        - sh
        - -c
        - "sleep 10; false"
