apiVersion: v1
kind: Pod
metadata:
  name: multiple-containers
spec:
  restartPolicy: Never
  containers:
    - name: container1
      image: ubuntu:16.04
      args:
        - sh
        - -c
        - "cat /etc/os-release; sleep 10; true"
    - name: container2
      image: ubuntu:16.04
      args:
        - sh
        - -c
        - "cat /etc/os-release; sleep 10; true"
