apiVersion: v1
kind: Pod
metadata:
  name: start-slow
spec:
  initContainers:
    - name: wait
      image: busybox
      args:
        - sh
        - -c
        - sleep 30
  containers:
    - name: start-slow
      image: nginx
