apiVersion: v1
kind: Pod
metadata:
  name: success
spec:
  restartPolicy: Never
  containers:
    - name: success
      image: ubuntu:16.10
      args:
        - sh
        - -c
        - "cat /etc/os-release; sleep 10; true"
