apiVersion: v1
kind: Pod
metadata:
  name: timeout
spec:
  restartPolicy: Never
  activeDeadlineSeconds: 5
  containers:
    - name: completed
      image: ubuntu:16.04
      args:
        - sh
        - -c
        - sleep 1000
