root_dir: .
resource_groups:
  - name: jobs
    resources:
      - jobs/*.yml
  - name: services
    resources:
      - services/*.yml
    depend:
      - jobs
    wait:
      - kind: job
        name: success
delete_namespace: true
