---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:{{.postgresTag}}
          env:
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: pgdata
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: pguser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: pgpassword
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    name: postgres
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
