apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  restartPolicy: Never
  containers:
    - name: pod1
      image: ubuntu:16.04
      args:
        - sh
        - -c
        - sleep 10000; true
