root_dir: .
resource_groups:
  - name: pod
    resources:
      - services/pod1.yml
  - name: nginx
    resources:
      - services/nginx.yml
    depend:
      - pod
    wait:
      - kind: pod
        name: pod1
delete_namespace: true
