apiVersion: batch/v1
kind: Job
metadata:
  name: job2
spec:
  template:
    metadata:
      name: job2
    spec:
      restartPolicy: Never
      containers:
        - name: job2
          image: ubuntu:16.04
          args:
            - sh
            - -c
            - sleep 10; true
