root_dir: .
resource_groups:
  - name: configs
    resources:
      - configs/*.yml
  - name: redis
    resources:
      - services/redis.yml
    depend:
      - configs
  - name: nginx
    resources:
      - services/nginx.yml
    depend:
      - redis
delete_namespace: true
