apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: deployment
    spec:
      containers:
        - name: deployment
          image: nginx:1.13.12
  revisionHistoryLimit: 10
