apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      name: statefulset
  serviceName: statefulset-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: statefulset
    spec:
      containers:
        - name: statefulset
          image: nginx
