root_dir: .
resource_groups:
  - name: jobs1
    resources:
      - jobs1/*.yml
  - name: services
    resources:
      - services/*.yml
    depend:
      - jobs1
    wait:
      - name: job1
        kind: job
        timeout: 10
delete_namespace: true
