root_dir: .
namespace: coruscant
variables:
  postgresTag: {{.postgresImageTag}}
  redisTag: 4-alpine
  postgresSidecarImage: postgres-sidecar:{{.appTag}}
  redisSidecarImage: redis-sidecar:{{.appTag}}
resource_groups:
  - name: configs
    resources:
      - ./configs/*.yml
    excludes:
      - ./configs/*ignore*
  - name: secrets
    resources:
      - ./secrets/*.yml
  - name: databases
    resources:
      - ./databases/*.yml
    depend:
      - configs
      - secrets
  - name: init-jobs
    resources:
      - ./jobs/*.yml
    depend:
      - databases
  - name: services
    resources:
      - ./services/*.yml
    depend:
      - init-jobs
    wait:
      - name: init-postgres
        kind: job
      - name: init-redis
        kind: job
