apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  backoffLimit: 1
  template:
    metadata:
      name: job1
    spec:
      restartPolicy: Never
      containers:
        - name: job1
          image: ubuntu:16.04
          args:
            - "false"
