apiVersion: batch/v1
kind: Job
metadata:
  name: init-redis
spec:
  template:
    metadata:
      name: init-redis
    spec:
      restartPolicy: Never
      containers:
        - name: init-redis
          image: {{.redisSidecarImage}}
