name: "[CI] JsLib"

concurrency:
  group: ci-jslib-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
    paths:
      - js/**
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd ./js
          bun install

      - name: Run test
        run: |
          cd ./js
          bun run check
          bun test
