name: "[Release] JsLib"

concurrency:
  group: release-jslib-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
          scope: "@anduintransaction"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd ./js
          bun install

      - name: Build
        run: |
          cd ./js
          bun run build

      - name: Publish
        run: |
          cd ./js
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
